# Generated by Django 4.0 on 2021-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='url',
            field=models.URLField(max_length=3000, null=True),
        ),
    ]
