# Generated by Django 4.0 on 2021-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_image_url',
            field=models.URLField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=3000),
        ),
    ]
