# Generated by Django 4.0 on 2021-12-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
